import React, { useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import DownloadButton from './DownloadButton';

import HomeImage from '../Assets/Home.png';
import TutorsImage from '../Assets/Tutors.png';
import TaskImage from '../Assets/Tasks.png';
import TaskDetailsImage from '../Assets/TaskDetails.png';
import RoadmapImage from '../Assets/Roadmap.png';
import TutorChatImage from '../Assets/TutorChat.png';

const AppShowcase = () => {
  const [activeSlide, setActiveSlide] = useState(0);

  const slides = [
    {
      image: HomeImage,
      title: "Smart Learning Dashboard",
      description: "Kickstart your learning with a personalized dashboard powered by AI insights."
    },
    {
      image: TutorsImage,
      title: "Virtual AI Tutors",
      description: "Interact with intelligent AI tutors trained to guide you through your academic journey."
    },
    {
      image: TaskImage,
      title: "Daily Learning Tasks",
      description: "Receive daily bite-sized tasks generated by AI, aligned with your goals and syllabus."
    },
    {
      image: TaskDetailsImage,
      title: "Detailed Task Insights",
      description: "Understand your tasks with contextual breakdowns and progress analytics."
    },
    {
      image: RoadmapImage,
      title: "AI-Powered Roadmaps",
      description: "Visualize your path to success with dynamic roadmaps generated just for you."
    },
    {
      image: TutorChatImage,
      title: "1-on-1 AI Chat Support",
      description: "Ask questions and get instant answers from your personal AI learning assistant."
    }
  ];

  const nextSlide = () => {
    setActiveSlide((prev) => (prev === slides.length - 1 ? 0 : prev + 1));
  };

  const prevSlide = () => {
    setActiveSlide((prev) => (prev === 0 ? slides.length - 1 : prev - 1));
  };

  return (
    <section id="app" className="py-20 bg-white dark:bg-slate-800 overflow-hidden">
      <div className="container mx-auto px-4">
        <div className="flex flex-col lg:flex-row items-center gap-12">
          <div className="lg:w-1/2 order-2 lg:order-1">
            <div className="relative">
              <div className="relative mx-auto w-60 h-[520px] bg-gray-900 rounded-3xl object-contain border-[8px] border-gray-900 shadow-xl overflow-hidden">
                {/* <div className="absolute top-0 w-full h-6 bg-gray-900 z-10 flex justify-center">
                  <div className="w-20 h-4 bg-gray-900 rounded-b-lg"></div>
                </div> */}

                {/* Carousel Container */}
                <div className="relative h-full bg-white overflow-hidden">
                  <div
                    className="flex w-full transition-transform duration-500 ease-in-out h-full"
                    style={{ transform: `translateX(-${activeSlide * 100}%)` }}
                  >
                    {slides.map((slide, index) => (
                      <div
                        key={index}
                        className="w-full flex-shrink-0 h-full"
                      >
                        <img
                          src={slide.image}
                          alt={slide.title}
                          className="w-full h-full object-contain"
                        />
                      </div>
                    ))}
                  </div>

                  {/* Dots */}
                  <div className="absolute bottom-5 left-0 right-0 flex justify-center space-x-2">
                    {slides.map((_, index) => (
                      <button
                        key={index}
                        onClick={() => setActiveSlide(index)}
                        className={`w-2 h-2 rounded-full ${activeSlide === index ? 'bg-white' : 'bg-white/50'
                          }`}
                        aria-label={`Go to slide ${index + 1}`}
                      />
                    ))}
                  </div>
                </div>
              </div>

              {/* Prev/Next */}
              <button
                title='previous'
                onClick={prevSlide}
                className="absolute top-1/2 -left-4 -translate-y-1/2 w-10 h-10 bg-white dark:bg-slate-700 rounded-full shadow-md flex items-center justify-center text-gray-800 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-slate-600 transition-colors"
              >
                <ChevronLeft size={20} />
              </button>
              <button
                title='next'
                onClick={nextSlide}
                className="absolute top-1/2 -right-4 -translate-y-1/2 w-10 h-10 bg-white dark:bg-slate-700 rounded-full shadow-md flex items-center justify-center text-gray-800 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-slate-600 transition-colors"
              >
                <ChevronRight size={20} />
              </button>
            </div>
          </div>

          <div className="lg:w-1/2 order-1 lg:order-2 text-center lg:text-left">
            <h2 className="text-3xl md:text-4xl font-bold mb-6">
              Experience the{" "}
              <span className="bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                Next Level
              </span>{" "}
              of Learning
            </h2>

            <div className="space-y-6 mb-8">
              <div>
                <h3 className="text-xl font-semibold mb-2">
                  {slides[activeSlide].title}
                </h3>
                <p className="text-gray-600 dark:text-gray-300 text-lg">
                  {slides[activeSlide].description}
                </p>
              </div>

              <ul className="space-y-3">
                <li className="flex items-start">
                  <span className="h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 flex items-center justify-center mr-2">✓</span>
                  <span>Available for Android devices</span>
                </li>
                <li className="flex items-start">
                  <span className="h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 flex items-center justify-center mr-2">✓</span>
                  <span>Free download, no account required to start</span>
                </li>
                <li className="flex items-start">
                  <span className="h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 flex items-center justify-center mr-2">✓</span>
                  <span>Regular updates with new AI capabilities</span>
                </li>
              </ul>
            </div>

            <div className="flex justify-center lg:justify-start">
              <DownloadButton size="lg" />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AppShowcase;
